### ISSUE TITLE
Kills process if DataDog on status code

### ISSUE THREAD

**Issue by apoydence** [DataDog/datadog-firehose-nozzle#33]
It looks like the nozzle will die if DataDog returns a status code it wasn't expecting:

https://github.com/DataDog/datadog-firehose-nozzle/blob/108e86daf53b6e4f59d392c9a554fa6e55a62ca8/datadogclient/datadog_client.go#L141-L147

https://github.com/DataDog/datadog-firehose-nozzle/blob/1d8bd1368ece99b67245f00168ab310998334738/datadogfirehosenozzle/datadog_firehose_nozzle.go#L101-L106

Is this the desired behavior? It implies that if DataDog experiences an issue, it will trickle down through everyone's nozzle and starting causing processes to die. I suspect it would be better to log an error without killing the process.

/cc @bradylove

**Comment by gmmeyer** [comment]
Hey @apoydence! 

Thank you very much for the bug report! 

This is a very bad bug, I understand that. However, this bug was fixed! It was fixed in this [Pull Request](https://github.com/DataDog/datadog-firehose-nozzle/pull/13/files#diff-07bcb66e36fc16d3e61b6669735b261bL103)

If you're still experiencing this error, please upgrade your nozzle. The most recent release of the nozzle is [67](https://github.com/DataDog/datadog-firehose-nozzle-release/releases/tag/67), and this bug has been resolved since release [64](https://github.com/DataDog/datadog-firehose-nozzle-release/releases/tag/64). 

Since it's been resolved, you don't mind if I close this issue, do you? 😃 

Thank you again!

(Since you cc'd @bradylove I'll cc him in as well)

**Comment by apoydence** [comment]
Thanks! I'll recommend deploying the latest release.
